[package]
name = "egomoose/rthro-scaler"
description = "https://github.com/EgoMoose/rbx-rthro-scaler"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dependencies]
Deque = "egomoose/deque@0.2.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"